"use client";

import { useEffect, useRef } from "react";
import { CloseIcon } from "./icons";

type MemoryDialogProps = {
  open: boolean;
  onClose: () => void;
};

const memoryItems = [
  {
    title: "WHAT YOU TELL MATEO",
    description:
      "Saved word for word as something Leo shared. If it mentions an event and a day, Emori keeps that too.",
    tone: "ring",
  },
  {
    title: "BETWEEN CONVERSATIONS",
    description:
      "Nothing from a chat window is carried over. When a new conversation opens, Emori looks for what matters now.",
    tone: "muted",
  },
  {
    title: "MATEO’S REPLIES",
    description:
      "Written by AI, guided by Mateo’s own stories and by what Leo shared. Labeled as generated; never becomes one of Mateo’s memories.",
    tone: "solid",
  },
];

export function MemoryDialog({ open, onClose }: MemoryDialogProps) {
  const closeButtonRef = useRef<HTMLButtonElement>(null);

  useEffect(() => {
    if (!open) return;
    const previousFocus = document.activeElement as HTMLElement | null;
    closeButtonRef.current?.focus();

    const handleKeyDown = (event: KeyboardEvent) => {
      if (event.key === "Escape") onClose();
    };

    document.addEventListener("keydown", handleKeyDown);
    return () => {
      document.removeEventListener("keydown", handleKeyDown);
      previousFocus?.focus();
    };
  }, [open, onClose]);

  if (!open) return null;

  return (
    <div className="dialog-layer" role="presentation" onMouseDown={onClose}>
      <section
        className="memory-dialog"
        role="dialog"
        aria-modal="true"
        aria-labelledby="memory-dialog-title"
        onMouseDown={(event) => event.stopPropagation()}
      >
        <button ref={closeButtonRef} className="dialog-close" type="button" onClick={onClose} aria-label="Close memory explanation">
          <CloseIcon />
        </button>
        <h2 id="memory-dialog-title">How Emori remembers</h2>
        <p className="dialog-subtitle">What happens behind every answer.</p>

        <div className="memory-timeline">
          {memoryItems.map((item) => (
            <article className="memory-item" key={item.title}>
              <span className={`timeline-dot timeline-dot--${item.tone}`} aria-hidden="true" />
              <div>
                <h3>{item.title}</h3>
                <p>{item.description}</p>
              </div>
            </article>
          ))}
        </div>

        <div className="memory-legend" aria-label="Memory source key">
          <span><i className="legend-ring" />Shared by Leo</span>
          <span><i className="legend-story">✣</i>Mateo’s own stories</span>
          <span><i className="legend-solid" />Generated by AI</span>
        </div>
      </section>
    </div>
  );
}
